### ISSUE TITLE
Getting "Profile" is not defined

### ISSUE THREAD

**Issue by madeyexz** [Squuv/WifiBF#6]
Hello, thanks for the amazing tool first!

But i encountered an error when i was trying to use it on my macOS
It says: "Profile" is not defined
![image](https://user-images.githubusercontent.com/45984618/77220042-d578d400-6b76-11ea-8c60-83ac404de5b3.png)
 
Can you help me solve it?

**Comment by oToToT** [comment]
Maybe you should install pywifi first.

**Comment by faycal-gh** [comment]
u should install comtypes and iface :
pip install comtypes
pip install iface
